name: CI/CD Pipeline for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

        # Paso 3: Cache de dependencias
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: bun install

      # Paso 5: Ejecutar ESLint
      - name: Run ESLint
        run: bun run lint

      # Paso 6: Ejecutar pruebas
      - name: Run tests
        run: bun test

      # Paso 7: Build del proyecto
      - name: Build project
        run: bun run build

      # Paso 8: Verificar el build
      - name: Check build output
        run: |
          if [ -d ".next" ]; then
            echo "Build successful!"
          else
            echo "Build failed!"
            exit 1
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: bun install

      # Paso 4: Build del proyecto
      - name: Build project
        run: bun run build

      # Paso 5: Desplegar en Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Usa el token de Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Opcional: ID de la organización
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Opcional: ID del proyecto
